const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
// const GET_PRODUCTS = "GET_PRODUCTS";
// const GET_CART = "GET_CART";
const SET_PRODUCTS = "SET_PRODUCTS";
const SET_CART = "SET_CART";

export default { SET_PRODUCTS, SET_CART, ADD_TO_CART, REMOVE_FROM_CART }
